name: Deploy Bot

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu environment for the job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js version 16 (adjust if needed)

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          npm install  # Install all dependencies listed in package.json

      # Step 4: Start the Bot
      - name: Start the Bot
        run: |
          npm install -g pm2  # Install PM2 for process management
          pm2 start index.js --name "Queen-Ruva"  # Start bot using PM2
          pm2 save  # Save the PM2 process to keep it running
